global:
  scrape_interval: 15s

scrape_configs:
  - job_name: trading_app
    static_configs:
      - targets: ["trading:8000"]

  - job_name: training_app
    static_configs:
      - targets: ["training:8001"]

  - job_name: redis
    static_configs:
      - targets: ["redis:6379"]
